import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GetServerSideProps } from "next"
import Link from 'next/link'

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch(`http://192.168.4.1/api/id`)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  const nameres = await fetch(`http://192.168.4.1/api/name`)
  const namedata = await nameres.json()

  if (!namedata) {
    return {
      notFound: true,
    }
  }

  const pkres = await fetch(`http://192.168.4.1/api/pubkey`)
  const pkdata = await pkres.json()

  if (!pkdata) {
    return {
      notFound: true,
    }
  }

  return {
    props: { id: data.id, name: namedata.name, pubkey: pkdata.pubkey }, // will be passed to the page component as props
  }
}

type Props = {
  id: string,
  pubkey: string,
  name: string
}

const Home: React.FC<Props> = (props) => {
  // todo: fetch this from /api/id
  //const myID = "https://boring.surf/p/" + process.env[varName];
  const myID = "https://boring.surf/p/" + props.id
  return (
    <div className={styles.container}>
      <Head>
        <title>{props.name}</title>
        <meta name="description" content="Generated by sentient ai overlord 4233" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to: {props.name}</h1>
        <h1 className={styles.title}>
          <a href={myID}>boring.surf</a>
        </h1>
        <h2>pubkey={props.pubkey}</h2>
        <h1 className={styles.title}>
          <Link href="/api/reboot">Reboot it</Link>
        </h1>

      </main>

      <footer className={styles.footer}>

        <a
          href="https://unconfigured.insecure.boring.surf:19531/browse"
        >go here bru,  to watch the logs..</a>
      </footer>
    </div>
  )
}

export default Home